[package]
name = "drone-agility-challenge"
version = "0.3.1"
edition = "2021"

[dependencies]
bevy = { version = "0.10.1", features = ["wayland"] }
rand = "0.8"
bevy_prototype_lyon = "0.8"
bevy_rapier2d = "0.21.0"
bevy_editor_pls = "0.4.0"
